source 'https://github.com/CocoaPods/Specs'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'BBAlert_Example' do
  pod 'BBAlert', :path => '../'
  pod 'Reusable'
  
  pod 'SwiftLint'

  target 'BBAlert_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  
  end
end
